version: "3.8"
services:
  frontend:
    image: sachin529/multi-tier-frontend:latest
    ports:
      - "8080:80"

  backend:
    image: sachin529/multi-tier-backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

