version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

